server:
    port: 8000
spring:
  devtools:
    livereload:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/board?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis:
  config-location: classpath:config/myBatis.xml

jwt:
    secret_key: secret_key_secret_key_secret_key_secret_key_secret_key_secret_key_secret_key_
    expTime: 30000
#  expTime: 86400000
  #1000*60*60*24


